name = "OpenStreetMapIO"
uuid = "005c2571-dbef-4654-b731-b11a1a12058a"
version = "0.1.0"
authors = ["MOVIRO"]

[deps]
CodecLz4 = "5ba52731-8f18-5e0d-9241-30f10d1ec561"
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
CodecLz4 = "0.4.6"
CodecXz = "0.7.4"
CodecZlib = "0.7.8"
CodecZstd = "0.8.6"
ProtoBuf = "1.2.0"
XML = "0.3.8"
julia = ">=1.10, <2.0"
